Add code coverage analysis
tatools/demo-python pull request #10
Opened 2017-06-06 13:29 UTC by ivan-podorozhnyi

Added requirements-dev.txt for Python dependencies with code coverage.

Updated `verify_project.sh` script to run tests with code coverage.

Updated `README.md`.

Updated `.travis.yml`.

Affects #3

2017-06-06 17:56 UTC, extsoft requested changes
@ivan-podorozhnyi please fix my comments.

2017-06-06 17:56 UTC, extsoft commented on README.md
> +2. Run `pip install -r requirements-dev.txt` to install required Python's dependencies.
We have to support two installations:
- for run - use `requirements.txt`
- for development - use `requirements.txt` and `requirements-dev.txt`

2017-06-06 17:56 UTC, extsoft commented on README.md
> +2. Run `py.test --cov=demo_python_at tests/` within your virtual environment to run tests with coverage.
This command runs unit tests, but this section about automated tests in `demo_python_at`. Please restore this paragraph.

2017-06-06 17:56 UTC, extsoft commented on requirements-dev.txt
> +pytest==3.1.1
This dependency is specified in `requirements.txt`. Don't duplicate dependencies.

2017-06-06 17:56 UTC, extsoft commented on requirements-dev.txt
> +coverage==4.4.1
Don't add all output from `pip freeze`. Please add only packages that you installed with `pip install`.

2017-06-07 08:20 UTC, ivan-podorozhnyi commented
@extsoft Please check the changes.

2017-06-08 15:26 UTC, AntonKarabaza requested changes
@ivan-podorozhnyi Take a look at my comments.

2017-06-08 15:26 UTC, AntonKarabaza commented on verify_project.sh
> +if command command coverage >/dev/null 2>&1 ; then
@ivan-podorozhnyi Please, fix `command command coverage` call.

2017-06-08 15:26 UTC, AntonKarabaza commented on .travis.yml
> +  - pip install -r requirements-dev.txt
@ivan-podorozhnyi Please, in commit message specify that dependencies will be installed both from `requirements.txt` and  `requirements-dev.txt`.

2017-06-08 15:26 UTC, AntonKarabaza commented on verify_project.sh
> +if command command coverage >/dev/null 2>&1 ; then
Please, fix `command command coverage` call.

2017-06-08 15:26 UTC, AntonKarabaza commented on .travis.yml
> +  - pip install -r requirements-dev.txt
Please, in commit message specify that dependencies will be installed both from `requirements.txt` and  `requirements-dev.txt`.

2017-06-09 07:17 UTC, ivan-podorozhnyi commented
@AntonKarabaza Please check my last changes.

2017-06-09 11:42 UTC, AntonKarabaza approved these changes

2017-06-09 11:43 UTC, AntonKarabaza commented
@ivan-podorozhnyi  Good. Thank you!

2017-06-09 17:54 UTC, extsoft requested changes
@ivan-podorozhnyi 
Some additional comments:
- all commits except 76114e1c8e3c0261219461810fa7242c98445698 have too general subject

2017-06-09 17:54 UTC, extsoft commented on requirements-dev.txt
> +coverage==4.4.1
Do we really need `coverage` here?

2017-06-09 17:54 UTC, extsoft commented on README.md
> +2. Run `pip install -r requirements.txt` or `pip install -r requirements-dev.txt`  to install required Python's dependencies.
`How to install?` section is about automated tests. Why do you add development details here?

2017-06-09 17:54 UTC, extsoft commented on verify_project.sh
> +if command coverage >/dev/null 2>&1 ; then
We have to measure coverage each time we run unit tests.

2017-06-12 12:43 UTC, ivan-podorozhnyi commented on requirements-dev.txt
> +coverage==4.4.1
@extsoft Moved coverage and pytest-cov dependencies to `requirements.txt`.

2017-06-12 12:44 UTC, ivan-podorozhnyi commented on README.md
> +2. Run `pip install -r requirements.txt` or `pip install -r requirements-dev.txt`  to install required Python's dependencies.
@extsoft Removed everything.

2017-06-12 12:45 UTC, ivan-podorozhnyi commented on verify_project.sh
> +if command coverage >/dev/null 2>&1 ; then
@extsoft Clear, now al tests run with coverage.

2017-06-13 10:18 UTC, extsoft requested changes
@ivan-podorozhnyi please work on my comments.

2017-06-13 10:18 UTC, extsoft commented on verify_project.sh
> +py.test --cov=demo_python_at
Unit testing has to be first.

2017-06-13 10:18 UTC, extsoft commented on requirements.txt
> +coverage==4.4.1
pip installs `coverage` automatically when it installs `pytest-cov`. Please remove `coverage` from the requirements.txt.

2017-06-13 10:18 UTC, extsoft commented on requirements.txt
> +pytest-cov==2.5.1
This has to migrate to `requirements-dev.txt` as this is only dev dependency.

2017-06-13 11:31 UTC, ivan-podorozhnyi commented on requirements.txt
> +pytest-cov==2.5.1
@extsoft But you said that we have to measure coverage each time we run unit tests.
command `py.test --cov=demo_python_at` runs all tests inside our projects with coverage.
Do I have to return back to version with installed library check?
```
if command coverage >/dev/null 2>&1 ; then
    py.test --cov=demo_python_at
else 
    py.test tests
fi
```

2017-06-13 11:33 UTC, extsoft commented on requirements.txt
> +pytest-cov==2.5.1
We have to run unit test only: `py.test tests`.

2017-06-13 11:36 UTC, ivan-podorozhnyi commented on requirements.txt
> +pytest-cov==2.5.1
@extsoft Understood, thanks.

2017-06-13 12:18 UTC, ivan-podorozhnyi commented
@extsoft Now tests run before flake8 checks, pytest-cov moved to dev dependencies.

2017-06-15 10:30 UTC, extsoft approved these changes

2017-06-15 10:30 UTC, merged