Add and configure setup.py
tatools/demo-python pull request #11
Opened 2017-06-07 12:05 UTC by AntonKarabaza

Affects #4

2017-06-09 13:20 UTC, ivan-podorozhnyi requested changes
@AntonKarabaza I suggest its better to use script to read dependencies in`install-required`field from `requirements.txt`.
Check: https://github.com/ets-labs/python-dependency-injector/blob/master/setup.py - it looks good. 
Also I think `def read(fname):` can be replaced with similar script (you can find it there too). But second is up to you, you can accept my idea or keep yours.

2017-06-09 13:44 UTC, AntonKarabaza commented
@ivan-podorozhnyi Please, take a look now.

2017-06-09 13:45 UTC, ivan-podorozhnyi approved these changes
@AntonKarabaza Looks good, thank you!

2017-06-09 17:59 UTC, extsoft requested changes

2017-06-09 17:59 UTC, extsoft commented on setup.py
> +    version="0.1",
Use Semantic versioning here. Set `0.1.0` version.

2017-06-12 08:27 UTC, AntonKarabaza commented
@extsoft Versioning is changed to Semantic and now has the form `0.1.0`.

2017-06-12 13:07 UTC, AntonKarabaza commented
@extsoft Before merge this pull request #18 have to be merged.

2017-06-15 10:31 UTC, extsoft commented
> @extsoft Before merge this pull request #18 have to be merged.
@AntonKarabaza done.

2017-06-15 10:42 UTC, AntonKarabaza commented
@extsoft Branch rebased and ready to merge.

2017-06-15 11:43 UTC, extsoft approved these changes

2017-06-15 11:44 UTC, merged