Configure pylint
tatools/demo-python pull request #12
Opened 2017-06-07 13:14 UTC by ivan-podorozhnyi

Added pylint dependency to `requirements-dev.txt`.

Updated `verify_project.sh` script to run pylint.

Affects #5

2017-06-07 14:41 UTC, ivan-podorozhnyi commented
@extsoft This issue is not solved yet. pylint call in `verify_project.sh` exits with error code 24 and I can't find out the reason now. I will finish it soon.

2017-06-07 15:09 UTC, ivan-podorozhnyi commented
@extsoft Please check my last commit. We can add pylint configuration file later if needed.

2017-06-08 15:10 UTC, ivan-podorozhnyi commented
@extsoft I found the source of exit codes problem of pylint. Pylint exits with 0 exit code when our code is absolutely correct i.e. no warnings, errors etc. were found. 
For more details you can check https://docs.pylint.org/en/1.6.0/run.html section "Exit codes".
And in our current project pylint found black-listed name of module `foo.bar` and exits with exit code 16. That's why I added `--disable=all` flag. Pylint runs and gives no error exit code but in fact it checks nothing.
In addition we will need to add `.pylintrc` configuration file to our project. Please let me know if it's ok. I can make changes accordingly.

2017-06-08 21:02 UTC, extsoft commented
@ivan-podorozhnyi 
1. Please create `.pylintrc`if you think we need this file.
2. `--disable=all` means don't check. It's very bad idea. So, please remove this.
3. Close #14 and then continue with this.

P.S.
@ivan-podorozhnyi next time please ask such questions in the task, not in the pull request. I think you faced these questions before a pull request. That's why we have to discuss them not in the pull request.

2017-06-09 09:07 UTC, ivan-podorozhnyi commented
@extsoft Changes applied. Please merge #15 before reviewing this pull request.

2017-06-15 11:52 UTC, AntonKarabaza approved these changes

2017-06-15 12:24 UTC, extsoft requested changes
@ivan-podorozhnyi please take o look for my comments.

2017-06-15 12:24 UTC, extsoft commented on verify_project.sh
> +pylint tests/
@ivan-podorozhnyi we don't need to check unit tests.

2017-06-15 12:24 UTC, extsoft commented on .pylintrc
> +overgeneral-exceptions=Exception
@ivan-podorozhnyi please add an empty line at the end of the file.

2017-06-15 13:22 UTC, ivan-podorozhnyi commented
@extsoft Unit tests check was removed and empty line was added at the end of `.pylintrc`. Please confirm.

2017-06-15 13:24 UTC, extsoft approved these changes

2017-06-15 13:24 UTC, merged

2017-06-15 13:25 UTC, extsoft commented
@ivan-podorozhnyi accepted. Great job!