Enable D102 rule for pydocstyle
tatools/demo-python pull request #28
Opened 2017-06-16 14:30 UTC by AntonKarabaza

Add docstrings for public methods.
Modify .pydocstyle to enable D102 rule but ignore D212 rule to
resolve conflicting rules.

2017-06-19 11:01 UTC, ivan-podorozhnyi requested changes
@AntonKarabaza Please look at my comments.

2017-06-19 11:01 UTC, ivan-podorozhnyi commented on .pydocstyle
> +ignore = D100,D101,D103,D104,D212
@AntonKarabaza Please add an empty line at the end of the file.

2017-06-19 11:01 UTC, ivan-podorozhnyi commented on demo_python_at/commons/message.py
> +        :return: True if message length greater than 0
@AntonKarabaza Please correct grammar mistakes. Its right to say "`is` greater than".

2017-06-20 08:42 UTC, AntonKarabaza commented
@ivan-podorozhnyi 
Empty line added in the end of `.pydocstyle`
Grammar mistakes corrected in `demo_python_at/commons/message.py`

2017-06-20 08:43 UTC, ivan-podorozhnyi commented
@AntonKarabaza Thank you!

2017-06-20 08:43 UTC, ivan-podorozhnyi approved these changes

2017-06-20 11:22 UTC, extsoft commented
@AntonKarabaza please fix conflicts.

2017-06-20 11:38 UTC, AntonKarabaza commented
@extsoft conflicts resolved.

2017-06-20 12:35 UTC, extsoft approved these changes

2017-06-20 12:36 UTC, merged